name: publish Docker images

on:
  release:
    types: [published]

jobs:
  build_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest tag
        uses: docker/build-push-action@v2
        with:
          file: ./docker/eolearn.dockerfile
          push: true
          tags: sentinelhub/eolearn:latest

      - name: Build and push latest-examples tag
        uses: docker/build-push-action@v2
        with:
          file: ./docker/eolearn-examples.dockerfile
          push: true
          tags: sentinelhub/eolearn:latest-examples

      - name: Update Docker Hub description and readme
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: sentinelhub/eolearn
          short-description: "Official eo-learn Docker images with Jupyter notebook"
          readme-filepath: ./README.md
